name: highcharts_api_gen
version: 0.5.1
description: Code generator for highcharts package. It parses the api published by highcharts at http://api.highcharts.com/highcharts
dependencies:
  http: ^0.11.3
  args: ^0.13.4
